### ISSUE TITLE
Users can choose one of three emotions provided at logging in.

### ISSUE THREAD

**Issue by EuichangPark** [EuichangPark/shareme-final-project-#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users have options to choose an emotion depending on how they feel today.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![wireframe1](https://user-images.githubusercontent.com/96793078/163043124-ab2781d5-a25c-4d88-af37-690f054ebd05.PNG)
![wirefram2](https://user-images.githubusercontent.com/96793078/163043126-8b81e09e-1344-4b50-a052-e55de62f8d4a.PNG)
![emotionscard](https://user-images.githubusercontent.com/96793078/163047996-a0f1049d-3cb5-4eea-b2e4-00e41f8d78fe.PNG)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render navbar
- [x] Create components for three emotions cards (joyful, Love, and Feeling Down)
- [x] When the card has hovered it flips and updates the component to show similar emotions to the card.
- [x] When the card is clicked it changes the page to feeds and posts.
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
